name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        NOTE: If your issue is a security concern, please send an email to security@gitea.io instead of opening a public issue
  - type: input
    id: version
    attributes:
      label: Gitea version
      description: Which version (or commit ref) of Gitea are you using?
    validations:
      required: false
  - type: dropdown
    id: database
    attributes:
      label: Database
      description: Which database are you using?
      options:
        - PostgreSQL
        - MySQL
        - MSSQL
        - SQLite
    validations:
      required: false
